name: unionchat
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.16+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  openapi:
    git:
      url: "http://git.lvdunhb.com/im/im-openapi.git"
      ref: "master"
  cupertino_icons: ^1.0.2
  logger: ^1.3.0
  shared_preferences: ^2.0.20
  flutter_easyloading: ^3.0.5
  flutter_webrtc: ^0.9.46
  photo_view: ^0.14.0
  http: ^1.1.0
  cached_network_image: ^3.2.3
  azlistview_plus: 3.0.0
  lpinyin: ^2.0.3 #?
  carousel_slider: ^4.2.1
  video_player: ^2.7.0

  intl: ^0.18.0
  web_socket_channel: ^2.4.0
  scan: ^1.6.0 #?
  image_picker: ^1.0.1
  permission_handler: ^10.3.0
  qr_flutter: ^4.1.0
  image_cropper: ^5.0.0
  flutter_localizations:
    sdk: flutter
  flutter_sound: ^9.2.13
  video_thumbnail: ^0.5.3 #?
  uuid: ^3.0.7
  provider: ^6.0.5
  fixnum: ^1.1.0
  sqflite_common_ffi: ^2.2.5
  crypto: ^3.0.3
  file_picker: ^5.3.1
  badges: ^3.1.1
  audioplayers: ^5.2.0
  record: ^4.4.4
  getwidget: ^3.1.1
  image_gallery_saver: ^2.0.3
  extended_image: ^8.1.1

  url_launcher: ^6.1.7
  flutter_speed_dial: ^7.0.0
  chewie: ^1.5.0
  device_info_plus: ^9.0.2
  package_info_plus: ^4.0.2
  share_plus: ^7.0.2
  vibration: ^1.8.0
  dart_vlc: ^0.4.0
  image_editor: ^1.3.0
  connectivity_plus: ^4.0.2
  webview_flutter: ^4.2.2
  webview_flutter_android: ^3.12.0
  webview_flutter_wkwebview: ^3.9.2
  screenshot: ^2.1.0
  easy_localization: ^3.0.2
  desktop_drop: ^0.4.1
  emoji_picker_flutter: ^1.6.1
  desktop_multi_window: ^0.2.0
  openinstall_flutter_plugin: ^2.4.0
  tpns_flutter_plugin:
    git:
      url: https://github.com/TencentCloud/TPNS-Flutter-Plugin
      ref: V1.2.6
  encrypt: ^5.0.1
  local_notifier: ^0.1.5
  wechat_assets_picker: ^8.5.0

  intl_phone_field: ^3.2.0

  pasteboard: ^0.2.0
  window_manager: ^0.3.5
  tray_manager: ^0.2.0
  pointycastle: ^3.7.3
  animations: ^2.0.7
  video_compress: ^3.1.0
  flutter_image_compress: ^2.0.4
  image: ^4.0.17
  flutter_ringtone_player: ^3.2.0
  fc_native_video_thumbnail: ^0.5.1
  wakelock: ^0.6.2
  reorderables: ^0.6.0
  open_file: ^3.3.2
  dio: ^5.3.2
  flutter_spinkit: ^5.2.0
  marquee: ^2.2.3
  flutter_html: ^3.0.0-beta.2
  flutter_swipe_action_cell: ^3.1.2
  scrollable_positioned_list: ^0.3.8
  image_editor_plus: ^1.0.3
  image_painter: ^0.6.1
  web3dart: ^2.7.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  json_annotation: ^4.8.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  expandable: ^5.0.1


# intl升级后删除 不推荐
dependency_overrides:
  intl: ^0.17.0
  win32: ^5.0.0
  http: ^0.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  test: ^1.24.1
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  fonts:
    - family: SourceHanSansCN
      fonts:
        - asset: assets/fonts/SourceHanSansCN-Normal.otf
          style: normal
  #   - family: Yahei
  #     fonts:
  #       - asset: assets/fonts/microsoft_yahei.ttc
  #         style: normal
  #   - family: Yahei1
  #     fonts:
  #       - asset: assets/fonts/microsoft_yahei_light.ttc
  #         style: normal
  assets:
    - assets/translations/
    - assets/images/
    - assets/images/mall/
    - assets/city_data/
    - assets/images/tabs/
    - assets/images/my/
    - assets/images/help/
    - assets/images/login/
    - assets/images/friend_circle/
    - assets/images/talk/
    - assets/mp3/
    - assets/images/vip/
    - assets/images/avatar/
    - assets/html/im-map/


